### hw_1

In [ ]:
import numpy as np

In [3]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [4]:
mean_a = np.mean(a, axis = 0)
mean_a

array([2. , 8.4])

### hw_2

In [6]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### hw_3

In [24]:
a_centered_sp = a_centered[:,0]@a_centered[:,1]
a_centered_sp / (a_centered.shape[0] - 1)


2.0

### hw_4

In [25]:
np.cov(a.T)[0][1]

2.0

###### 2.0 == 2.0